### ISSUE TITLE
Use inkscape to convert

### ISSUE THREAD

**Issue by dvzrv** [pure-data/pd-icon#2]
It would be more straight forward to only have one .svg in this repository as master and then compile the images on demand from it.

Inkscape can be used for that:

```
for _res in {16,32,48,64,96,128,256,512,1024}; do
  inkscape -z -e pd-${_res} -w ${_res} -h ${_res} icon.svg
done
```

This generates all the above sizes and has better image quality than imagemagick. :)

**Comment by danomatika** [comment]
>Inkscape can be used for that

This assumes you have inkscape installed, which I did not and don't feel like installing.

>has better image quality than imagemagick

For such a simple design, is it that much of a difference?

**Comment by danomatika** [comment]
This reminds me that the master files need to be cleaned up. There are a couple different SVGs, etc and we're only using one. I also did some hand-tweaking to a couple of files.

**Comment by dvzrv** [comment]
cool, thank you! :)
