### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by dvzrv** [pure-data/pd-icon#3]
For packaging purposes, it would be very awesome to have a "released" version of this repository, as it makes it easier to retrieve a checksummed version of the data contained in this repository.

Thanks a lot for the effort so far! :)

**Comment by danomatika** [comment]
This repo for was making the icon once and will not be versioned. The icon files are in the pure-data source repo and will probably not change there for some time.

**Comment by danomatika** [comment]
Also, I didn't intend this repo to become "official." It was mainly a way to generate an icon update idea for people to try out and discuss. It's more likely that we'll fold this into the main repo at some point, at least the master files.

**Comment by dvzrv** [comment]
On 2019-08-12 01:53:05 (-0700), Dan Wilcox wrote:
> Also, I didn't intend this repo to become "official." It was mainly a
> way to generate an icon update idea for people to try out and discuss.
> It's more likely that we'll fold this into the main repo at some
> point, at least the master files.

Okay, that sounds reasonable. Thanks for the explanation! :)

**Comment by mxa** [comment]
> This repo for was making the icon once and will not be versioned. The icon files are in the pure-data source repo and will probably not change there for some time.

Is it? I've searched the Pd source for *.svg and *.png and could not find the icon

**Comment by danomatika** [comment]
png and svg are used to create the *exported* types which are used by the GUI...

* xpm: /tcl
* icns: /mac/stuff
* gif: /tcl
* ico: /tcl
