### ISSUE TITLE
Inkscape has changed flags

### ISSUE THREAD

**Issue by mxa** [pure-data/pd-icon#4]
The Inkscape syntax is broken because Inkscape from Version 1.0 has changed its command line API

- `-z` is shorthand for `--without-gui` which is deprecated and should be removed.
- `-e` is ? (it throws an error)

with both `-z` and `-e` removed it still throws an error:

```
Cannot parse integer value “{16,32,48,64,96,128,256,512}” for -w
make: *** [Makefile:93: inkscape] Error 1
```

From looking at the [manual](https://wiki.inkscape.org/wiki/index.php?title=Using_the_Command_Line) I would have guessed it now should be like this:

```
# generate pngs from SVG directly using inkscape
inkscape:
	for _res in {16,32,48,64,96,128,256,512} ; do \
		inkscape --export-type="png" --export-filename=pd-$${_res}.png --export-width $${_res} --export-height $${_res} $(SRC_SVG) ; \
	done
```

however:
```
inkscape --export-type="png" --export-filename=pd-16.png --export-width 16 --export-height 16 $(SRC_SVG)
```
is working, so I guess it's something about the Makefile syntax

**Comment by mxa** [comment]
Code duplication madness, but works:

https://github.com/pure-data/pd-icon/pull/5

**Comment by danomatika** [comment]
What error do you get using the for loop and the updated syntax? The for loop syntax seems fine for me in zsh on macOS.

**Comment by mxa** [comment]
```
$ make inkscape
for _res in {16,32,48,64,96,128,256,512} ; do \
        inkscape --export-type="png" --export-filename=pd-${_res}.png --export-width ${_res} --export-height ${_res} masters/icon.svg ; \
done
Cannot parse integer value “{16,32,48,64,96,128,256,512}” for --export-width
make: *** [Makefile:93: inkscape] Error 1

```

**Comment by danomatika** [comment]
What shell are you using?

**Comment by mxa** [comment]
bash

**Comment by danomatika** [comment]
oh, this should probably be:

```shell
for _res in {16,32,48,64,96,128,256,512} ; do \
        inkscape --export-type="png" --export-filename=pd-$${_res}.png --export-width $${_res} --export-height $${_res} $(SRC_SVG) ; \
done
```

Note the `$${_res}` with two $...

**Comment by mxa** [comment]
yes, It has two $$ in the Makefile, but only one in the bash error output.

**Comment by danomatika** [comment]
Ok, well I don't have inkscape installed but what I can tell is that the loop works by echoing. I didn't write the makefile target as it was contributed by someone else.

Running:

```makefile
inkscape:
	for _res in {16,32,48,64,96,128,256,512} ; do \
		echo "inkscape -z -e pd-$${_res} -w $${_res} -h $${_res} $(SRC_SVG)" ; \
	done
```

Gives me:

```
% make inkscape
for _res in {16,32,48,64,96,128,256,512} ; do \
		echo "inkscape -z -e pd-${_res} -w ${_res} -h ${_res} masters/icon.svg" ; \
	done
inkscape -z -e pd-16 -w 16 -h 16 masters/icon.svg
inkscape -z -e pd-32 -w 32 -h 32 masters/icon.svg
inkscape -z -e pd-48 -w 48 -h 48 masters/icon.svg
inkscape -z -e pd-64 -w 64 -h 64 masters/icon.svg
inkscape -z -e pd-96 -w 96 -h 96 masters/icon.svg
inkscape -z -e pd-128 -w 128 -h 128 masters/icon.svg
inkscape -z -e pd-256 -w 256 -h 256 masters/icon.svg
inkscape -z -e pd-512 -w 512 -h 512 masters/icon.svg
```

Note: the makefile console output strips the first $ in the `$${_res}` arguments.

**Comment by mxa** [comment]
Not working for me:

```
 make inkscape
for _res in {16,32,48,64,96,128,256,512} ; do \
        echo "inkscape -z -e pd-${_res} -w ${_res} -h ${_res} masters/icon.svg" ; \
done
inkscape -z -e pd-{16,32,48,64,96,128,256,512} -w {16,32,48,64,96,128,256,512} -h {16,32,48,64,96,128,256,512} masters/icon.svg
```

Seems it's not iterating through the list, but taking the whole list as one variable including the commas...

**Comment by danomatika** [comment]
Yup, something is wrong with make or the shell or whatever. Dunno.

**Comment by mxa** [comment]
Works like this:

```
inkscape:
	for _res in 16 32 48 64 96 128 256 512 ; do \
		echo "inkscape -z -e pd-$${_res} -w $${_res} -h $${_res} $(SRC_SVG)" ; \
	done
```

**Comment by danomatika** [comment]
That works for me. Update your PR.

**Comment by danomatika** [comment]
...with the new inkscape syntax too. 👍

**Comment by danomatika** [comment]
I made a small edit, should work fine.

**Comment by chr15m** [comment]
> yes, It has two $$ in the Makefile, but only one in the bash error output.

For your reference, two dollars are used to escape the dollar so it is ignored by make itself and passed through to the shell part, which then performs the substitution.
